chaos:
    monkey:
        enabled: true
        watcher:
            controller: true
            repository: true
            restController: true
            service: true
management:
    endpoint:
        chaosmonkey:
            enabled: true
        chaosmonkeyjmx:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    profiles:
        active: chaos-monkey
